// Seed data for the demo build. In the production build this data lives in
// PostgreSQL and is served by the Node/Express REST API (see /server).

export const COMPANIES = [
  {
    id: 'c1',
    name: 'Northgate Global Solutions',
    logo: 'NG',
    color: '#2563eb',
    industry: 'Customer Experience BPO',
    size: '5,000 - 10,000 employees',
    hq: 'Taguig, Metro Manila, PH',
    website: 'northgate-bpo.example.com',
    verified: true,
    about:
      'Northgate runs voice and omnichannel customer experience programs for US telco, fintech and healthcare brands. 11 delivery sites across the Philippines, India and Colombia.',
  },
  {
    id: 'c2',
    name: 'Corebridge Contact Centers',
    logo: 'CB',
    color: '#0d9488',
    industry: 'Sales & Collections',
    size: '1,000 - 5,000 employees',
    hq: 'Cebu City, PH',
    website: 'corebridge.example.com',
    verified: true,
    about:
      'Outbound sales, lead qualification and first-party collections for North American clients. Known for one of the highest commission structures in the region.',
  },
  {
    id: 'c3',
    name: 'Helix Support Group',
    logo: 'HX',
    color: '#7c3aed',
    industry: 'Technical Support',
    size: '500 - 1,000 employees',
    hq: 'Bogotá, Colombia',
    website: 'helixsupport.example.com',
    verified: true,
    about:
      'Tier 1–3 technical support for SaaS and consumer hardware brands. Bilingual (EN/ES) delivery with a strong work-from-home footprint.',
  },
  {
    id: 'c4',
    name: 'Meridian Back Office',
    logo: 'MB',
    color: '#ea580c',
    industry: 'Back Office / Data',
    size: '200 - 500 employees',
    hq: 'Pune, India',
    website: 'meridianbo.example.com',
    verified: false,
    about:
      'Claims processing, medical coding, KYC and data annotation services for insurance and banking clients in the US and UK.',
  },
  {
    id: 'c5',
    name: 'Vantage Healthcare BPO',
    logo: 'VH',
    color: '#db2777',
    industry: 'Healthcare BPO',
    size: '1,000 - 5,000 employees',
    hq: 'Alabang, Muntinlupa, PH',
    website: 'vantage-health.example.com',
    verified: true,
    about:
      'HIPAA-compliant patient support, revenue cycle management and pharmacy support programs for US healthcare providers.',
  },
];

const D = (n) => new Date(Date.now() - n * 86400000).toISOString();

export const JOBS = [
  {
    id: 'j1',
    companyId: 'c1',
    title: 'Customer Service Representative - US Telco Account',
    category: 'Customer Service',
    campaign: 'Inbound Voice',
    level: 'Entry Level',
    setup: 'On-site',
    shift: 'Night Shift (US Hours)',
    location: 'Taguig, Metro Manila, PH',
    languages: ['English'],
    salaryMin: 25000,
    salaryMax: 32000,
    currency: 'PHP',
    period: 'month',
    seats: 120,
    experience: 'No BPO experience required',
    postedAt: D(1),
    featured: true,
    description:
      'Handle inbound calls for one of the largest US wireless carriers. You will assist customers with billing questions, plan changes, device troubleshooting and retention offers.',
    responsibilities: [
      'Answer inbound customer calls professionally and resolve issues on first contact',
      'Navigate multiple systems to verify accounts and process billing adjustments',
      'Offer relevant plan upgrades and retention packages',
      'Document every interaction accurately in the CRM',
    ],
    requirements: [
      'At least high school graduate (senior high / K-12 completers welcome)',
      'Good to excellent English communication skills',
      'Willing to work on a night shift and on shifting schedules',
      'Amenable to working on-site in Taguig',
    ],
    benefits: ['HMO on day 1 + 2 dependents', 'Night differential', 'Performance incentives up to PHP 8,000', 'Free shuttle service'],
  },
  {
    id: 'j2',
    companyId: 'c2',
    title: 'Outbound Sales Agent - Solar Campaign (High Commission)',
    category: 'Sales',
    campaign: 'Outbound Sales',
    level: 'Mid Level',
    setup: 'Hybrid',
    shift: 'Night Shift (US Hours)',
    location: 'Cebu City, PH',
    languages: ['English'],
    salaryMin: 28000,
    salaryMax: 45000,
    currency: 'PHP',
    period: 'month',
    seats: 45,
    experience: '1+ year outbound sales',
    postedAt: D(2),
    featured: true,
    description:
      'Own an outbound solar lead-generation and closing campaign for a US residential energy client. Uncapped commission on top of base pay.',
    responsibilities: [
      'Call warm leads from a predictive dialer and qualify homeowners',
      'Set appointments for field consultants and close simple deals over the phone',
      'Hit daily talk-time, conversion and quality targets',
    ],
    requirements: [
      'At least 1 year outbound sales or telemarketing experience',
      'Proven track record of hitting sales quota',
      'Strong objection-handling and closing skills',
    ],
    benefits: ['Uncapped commission (top earners PHP 90k+)', 'HMO after 30 days', 'Hybrid after 3 months', 'Monthly sales incentives'],
  },
  {
    id: 'j3',
    companyId: 'c3',
    title: 'Bilingual Technical Support Specialist (English / Spanish)',
    category: 'Technical Support',
    campaign: 'Inbound Voice',
    level: 'Mid Level',
    setup: 'Work From Home',
    shift: 'Mid Shift',
    location: 'Bogotá, Colombia (Remote)',
    languages: ['English', 'Spanish'],
    salaryMin: 3200000,
    salaryMax: 4500000,
    currency: 'COP',
    period: 'month',
    seats: 30,
    experience: '1+ year technical support',
    postedAt: D(3),
    featured: true,
    description:
      'Provide Tier 2 technical support for a US SaaS product across chat, email and voice, switching between English and Spanish depending on the customer.',
    responsibilities: [
      'Diagnose and resolve software, network and integration issues',
      'Escalate complex bugs to engineering with clean reproduction steps',
      'Maintain CSAT above 90% and adhere to SLA response times',
    ],
    requirements: [
      'C1 English and native-level Spanish',
      'Experience with ticketing tools (Zendesk, Freshdesk or similar)',
      'Stable home internet of at least 20 Mbps',
    ],
    benefits: ['100% work from home', 'Company-provided equipment', 'Private health insurance', 'Certification budget'],
  },
  {
    id: 'j4',
    companyId: 'c5',
    title: 'Healthcare Account Associate - Patient Support',
    category: 'Healthcare Support',
    campaign: 'Inbound Voice',
    level: 'Entry Level',
    setup: 'On-site',
    shift: 'Night Shift (US Hours)',
    location: 'Alabang, Muntinlupa, PH',
    languages: ['English'],
    salaryMin: 27000,
    salaryMax: 35000,
    currency: 'PHP',
    period: 'month',
    seats: 80,
    experience: 'Open to fresh graduates',
    postedAt: D(3),
    featured: false,
    description:
      'Support US patients with appointment scheduling, insurance verification and prescription refill requests for a national healthcare provider.',
    responsibilities: [
      'Verify patient insurance eligibility and benefits',
      'Schedule and reschedule appointments across provider networks',
      'Handle protected health information in line with HIPAA',
    ],
    requirements: [
      'Excellent English communication',
      'Detail-oriented, comfortable with strict compliance rules',
      'Healthcare or medical background is a plus but not required',
    ],
    benefits: ['HMO on day 1', 'PHP 20,000 signing bonus', 'Night differential', 'Paid HIPAA training'],
  },
  {
    id: 'j5',
    companyId: 'c4',
    title: 'Medical Coder (CPC Certified)',
    category: 'Back Office',
    campaign: 'Back Office',
    level: 'Mid Level',
    setup: 'Work From Home',
    shift: 'Day Shift',
    location: 'Pune, India (Remote)',
    languages: ['English'],
    salaryMin: 45000,
    salaryMax: 65000,
    currency: 'INR',
    period: 'month',
    seats: 15,
    experience: '2+ years medical coding',
    postedAt: D(5),
    featured: false,
    description:
      'Review clinical documentation and assign accurate ICD-10-CM, CPT and HCPCS codes for a US multi-specialty group.',
    responsibilities: [
      'Code inpatient and outpatient charts to a 95%+ accuracy standard',
      'Query providers when documentation is insufficient',
      'Meet daily production targets without sacrificing quality',
    ],
    requirements: ['CPC or CCS certification (active)', '2+ years of coding experience', 'Strong knowledge of ICD-10-CM and CPT'],
    benefits: ['Fully remote', 'Certification renewal paid', 'Quarterly quality bonus'],
  },
  {
    id: 'j6',
    companyId: 'c1',
    title: 'Team Leader - Customer Experience (Voice)',
    category: 'Team Lead / Supervisor',
    campaign: 'Inbound Voice',
    level: 'Team Lead',
    setup: 'On-site',
    shift: 'Night Shift (US Hours)',
    location: 'Taguig, Metro Manila, PH',
    languages: ['English'],
    salaryMin: 45000,
    salaryMax: 60000,
    currency: 'PHP',
    period: 'month',
    seats: 6,
    experience: '2+ years as TL in a BPO',
    postedAt: D(6),
    featured: false,
    description:
      'Lead a team of 15–20 customer service representatives on a US telco program. Own team KPIs, coaching and attrition.',
    responsibilities: [
      'Run daily huddles, coaching sessions and performance reviews',
      'Own team AHT, CSAT, QA and attendance metrics',
      'Handle escalations and act as the client-facing point of contact',
    ],
    requirements: [
      'At least 2 years of team leader experience in a contact center',
      'Strong grasp of contact center metrics (AHT, CSAT, FCR, NPS)',
      'Proven coaching and people-management ability',
    ],
    benefits: ['Leadership development program', 'HMO + 3 dependents', 'Rice and clothing allowance'],
  },
  {
    id: 'j7',
    companyId: 'c2',
    title: 'Collections Specialist - First Party (US Accounts)',
    category: 'Collections',
    campaign: 'Outbound Collections',
    level: 'Mid Level',
    setup: 'On-site',
    shift: 'Night Shift (US Hours)',
    location: 'Cebu City, PH',
    languages: ['English'],
    salaryMin: 26000,
    salaryMax: 38000,
    currency: 'PHP',
    period: 'month',
    seats: 40,
    experience: '6 months collections or outbound',
    postedAt: D(7),
    featured: false,
    description:
      'Contact US consumers on early-stage delinquent accounts, negotiate payment arrangements and secure payments in full.',
    responsibilities: [
      'Negotiate payment plans within client and FDCPA guidelines',
      'Maintain call quality and compliance scores above 95%',
      'Hit monthly recovery targets',
    ],
    requirements: ['6 months+ collections or outbound calling', 'Excellent negotiation skills', 'Clean compliance record'],
    benefits: ['Recovery-based incentives', 'HMO after 30 days', 'Night differential'],
  },
  {
    id: 'j8',
    companyId: 'c3',
    title: 'Chat & Email Support Agent - E-commerce (Non-Voice)',
    category: 'Customer Service',
    campaign: 'Non-Voice / Chat',
    level: 'Entry Level',
    setup: 'Work From Home',
    shift: 'Shifting',
    location: 'Remote - LATAM',
    languages: ['English'],
    salaryMin: 900,
    salaryMax: 1200,
    currency: 'USD',
    period: 'month',
    seats: 25,
    experience: 'No experience required',
    postedAt: D(8),
    featured: false,
    description:
      'Handle up to 3 concurrent chats and an email queue for a fast-growing US e-commerce brand. Pure non-voice account.',
    responsibilities: [
      'Respond to customer chats and emails about orders, refunds and shipping',
      'Process returns and refunds in Shopify',
      'Keep first-response time under 2 minutes',
    ],
    requirements: ['Typing speed of 40+ WPM', 'Strong written English', 'Reliable internet and a quiet workspace'],
    benefits: ['100% remote', 'Paid training', 'Equipment allowance'],
  },
  {
    id: 'j9',
    companyId: 'c5',
    title: 'Quality Analyst - Healthcare Voice Program',
    category: 'Quality Assurance',
    campaign: 'Quality / Training',
    level: 'Mid Level',
    setup: 'Hybrid',
    shift: 'Night Shift (US Hours)',
    location: 'Alabang, Muntinlupa, PH',
    languages: ['English'],
    salaryMin: 35000,
    salaryMax: 48000,
    currency: 'PHP',
    period: 'month',
    seats: 8,
    experience: '1+ year QA in a contact center',
    postedAt: D(10),
    featured: false,
    description:
      'Audit recorded and live calls, calibrate with the client, and drive quality improvement plans for a HIPAA-regulated program.',
    responsibilities: [
      'Evaluate calls against the client scorecard and internal compliance rules',
      'Run weekly calibration sessions with operations and the client',
      'Publish quality dashboards and root-cause analyses',
    ],
    requirements: ['1+ year of QA experience in a BPO', 'Strong analytical and reporting skills', 'Excel / Google Sheets proficiency'],
    benefits: ['Hybrid setup', 'HMO on day 1', 'Six Sigma training sponsorship'],
  },
  {
    id: 'j10',
    companyId: 'c4',
    title: 'KYC / AML Analyst - UK Banking Client',
    category: 'Back Office',
    campaign: 'Back Office',
    level: 'Mid Level',
    setup: 'On-site',
    shift: 'Day Shift',
    location: 'Pune, India',
    languages: ['English'],
    salaryMin: 40000,
    salaryMax: 55000,
    currency: 'INR',
    period: 'month',
    seats: 20,
    experience: '1+ year KYC / AML',
    postedAt: D(11),
    featured: false,
    description:
      'Perform customer due diligence and enhanced due diligence checks for a UK retail bank, escalating suspicious activity where required.',
    responsibilities: [
      'Complete CDD/EDD reviews within SLA',
      'Screen customers against sanctions and PEP lists',
      'Raise internal suspicious activity reports',
    ],
    requirements: ['1+ year KYC/AML experience', 'Familiarity with sanctions screening tools', 'Graduate in any discipline'],
    benefits: ['Day shift (UK hours)', 'Transport allowance', 'Annual bonus'],
  },
  {
    id: 'j11',
    companyId: 'c1',
    title: 'Workforce Management (WFM) Real-Time Analyst',
    category: 'Workforce Management',
    campaign: 'Support Function',
    level: 'Mid Level',
    setup: 'On-site',
    shift: 'Shifting',
    location: 'Taguig, Metro Manila, PH',
    languages: ['English'],
    salaryMin: 32000,
    salaryMax: 45000,
    currency: 'PHP',
    period: 'month',
    seats: 4,
    experience: '1+ year WFM / RTA',
    postedAt: D(13),
    featured: false,
    description:
      'Monitor real-time queue health across multiple programs, manage intraday shrinkage and trigger escalations to hit service level.',
    responsibilities: [
      'Monitor service level, occupancy and adherence in real time',
      'Issue intraday alerts and recommend schedule adjustments',
      'Produce end-of-day intraday performance reports',
    ],
    requirements: ['Experience with Genesys, NICE IEX or Verint', 'Strong Excel skills', 'Comfortable working shifting schedules'],
    benefits: ['HMO on day 1', 'Shift allowance', 'Career path into capacity planning'],
  },
  {
    id: 'j12',
    companyId: 'c3',
    title: 'Trainer - Communications & Product (Voice Accounts)',
    category: 'Training',
    campaign: 'Quality / Training',
    level: 'Mid Level',
    setup: 'Hybrid',
    shift: 'Mid Shift',
    location: 'Bogotá, Colombia',
    languages: ['English', 'Spanish'],
    salaryMin: 4000000,
    salaryMax: 5500000,
    currency: 'COP',
    period: 'month',
    seats: 3,
    experience: '2+ years training in a BPO',
    postedAt: D(15),
    featured: false,
    description:
      'Deliver new-hire product and communications training for bilingual support programs and run refresher sessions driven by QA findings.',
    responsibilities: [
      'Facilitate new-hire training waves end to end',
      'Build training material and knowledge-base content',
      'Track and report on nesting and post-training performance',
    ],
    requirements: ['2+ years of BPO training experience', 'Excellent facilitation skills in English and Spanish'],
    benefits: ['Hybrid setup', 'Private health insurance', 'Annual learning budget'],
  },
];

export const USERS = [
  {
    id: 'u1',
    role: 'candidate',
    name: 'Maria Santos',
    email: 'maria@demo.com',
    password: 'demo1234',
    headline: 'Customer Service Representative - 3 years US telco experience',
    location: 'Quezon City, Metro Manila, PH',
    phone: '+63 917 555 0142',
    experienceYears: 3,
    skills: ['Inbound Voice', 'Billing Support', 'Retention', 'Zendesk', 'Salesforce CRM'],
    languages: ['English', 'Filipino'],
    shiftPreference: 'Night Shift (US Hours)',
    setupPreference: 'Hybrid',
    expectedSalary: '35,000 PHP / month',
    resumeName: 'Maria_Santos_CV.pdf',
    about:
      'BPO professional with 3 years of experience on US telco and fintech accounts. Consistently in the top 10% for CSAT. Looking to move into a senior or SME role.',
    createdAt: D(60),
  },
  {
    id: 'u2',
    role: 'recruiter',
    name: 'James Reyes',
    email: 'james@demo.com',
    password: 'demo1234',
    companyId: 'c1',
    title: 'Senior Talent Acquisition Specialist',
    location: 'Taguig, Metro Manila, PH',
    phone: '+63 917 555 0199',
    createdAt: D(120),
  },
  {
    id: 'u3',
    role: 'admin',
    name: 'Platform Admin',
    email: 'admin@demo.com',
    password: 'demo1234',
    createdAt: D(200),
  },
  {
    id: 'u4',
    role: 'candidate',
    name: 'Carlos Mendoza',
    email: 'carlos@demo.com',
    password: 'demo1234',
    headline: 'Bilingual Technical Support (EN/ES) - 2 years',
    location: 'Bogotá, Colombia',
    phone: '+57 310 555 0110',
    experienceYears: 2,
    skills: ['Tier 2 Support', 'Troubleshooting', 'Freshdesk', 'SaaS'],
    languages: ['English', 'Spanish'],
    shiftPreference: 'Mid Shift',
    setupPreference: 'Work From Home',
    expectedSalary: '4,000,000 COP / month',
    resumeName: 'Carlos_Mendoza_Resume.pdf',
    about: 'Bilingual technical support specialist focused on SaaS products. Strong troubleshooting and escalation discipline.',
    createdAt: D(40),
  },
  {
    id: 'u5',
    role: 'candidate',
    name: 'Angela Cruz',
    email: 'angela@demo.com',
    password: 'demo1234',
    headline: 'Team Leader - Voice Operations, 5 years BPO',
    location: 'Pasig City, Metro Manila, PH',
    phone: '+63 917 555 0177',
    experienceYears: 5,
    skills: ['People Management', 'Coaching', 'AHT/CSAT', 'Escalations'],
    languages: ['English', 'Filipino'],
    shiftPreference: 'Night Shift (US Hours)',
    setupPreference: 'On-site',
    expectedSalary: '55,000 PHP / month',
    resumeName: 'Angela_Cruz_CV.pdf',
    about: 'Team leader with 5 years in contact center operations, managing teams of up to 22 agents on US voice programs.',
    createdAt: D(25),
  },
];

export const APPLICATIONS = [
  { id: 'a1', jobId: 'j1', userId: 'u1', status: 'Interview', appliedAt: D(2), note: 'Applied via BPOHire' },
  { id: 'a2', jobId: 'j6', userId: 'u5', status: 'Shortlisted', appliedAt: D(4), note: '' },
  { id: 'a3', jobId: 'j3', userId: 'u4', status: 'Applied', appliedAt: D(1), note: '' },
  { id: 'a4', jobId: 'j1', userId: 'u5', status: 'Applied', appliedAt: D(1), note: '' },
  { id: 'a5', jobId: 'j2', userId: 'u1', status: 'Rejected', appliedAt: D(9), note: '' },
  { id: 'a6', jobId: 'j6', userId: 'u1', status: 'Applied', appliedAt: D(0), note: '' },
];

export const SAVED = [{ id: 's1', jobId: 'j3', userId: 'u1', savedAt: D(1) }];

export const THREADS = [
  {
    id: 't1',
    recruiterId: 'u2',
    candidateId: 'u1',
    jobId: 'j1',
    messages: [
      {
        id: 'm1',
        from: 'u2',
        text: 'Hi Maria, thanks for applying to the CSR role on our US telco account. Your telco background looks like a strong match. Are you available for a virtual interview this week?',
        at: D(2),
      },
      { id: 'm2', from: 'u1', text: 'Hi James, thank you! Yes, I am available Wednesday or Thursday, anytime after 2 PM.', at: D(2) },
      { id: 'm3', from: 'u2', text: 'Perfect. I have booked you for Thursday 3 PM. You will get the meeting link here shortly.', at: D(1) },
    ],
  },
  {
    id: 't2',
    recruiterId: 'u2',
    candidateId: 'u5',
    jobId: 'j6',
    messages: [
      {
        id: 'm4',
        from: 'u2',
        text: 'Hi Angela, we reviewed your profile for the Team Leader role. Could you share your current team size and your CSAT numbers?',
        at: D(3),
      },
    ],
  },
];
